---
title: "Estudios de posgrado/en el exterior"
---

Si está interesado/a en una carrera como investigador, dentro o fuera de la academia, y quisiera hacer una maestría y/o un doctorado lo primero que debe tener en cuenta es que aplicar a estos programas implica varios pasos importantes y toma tiempo. Además hay algunos aspectos importantes que pueden variar según el área de la economía que le interese---así que debería hablar sobre todo con los profesores que trabajen en esas áreas. 

## Algunas consideraciones generales

- Sin un buen resultado en el TOEFL y en el GRE difícilmente podrá entrar a un buen programa en el exterior---incluso en universidades de países no angloparlantes. Estos exámenes cuestan, prepararlos toma tiempo y no es raro tener que presentarlos más de una vez.

- Como estudiante extranjero va a ser más difícil entrar directamente a un programa de doctorado si solo tiene un título de pregrado. Puede ser más conveniente hacer primero una maestría, acá o en el extranjero, que después le permita aplicar a un programa de doctorado con una mayor probabilidad de éxito.

  - Otra opción es demostrar experiencia en investigación. Es común que los estudiantes pasen un tiempo como asistentes de investigación/predocs antes de empezar un doctorado. Esto además es muy útil para obtener buenas cartas de recomendación---que necesitará para sus aplicaciones.

- Hablar con estudiantes colombianos---y sobre todo con aquellos graduados de programas de Univalle que estén cursando actualmente el tipo de posgrado que le interesa---puede ser muy útil.

- La mayoría de programas de doctorado ofrecen algún tipo de financiación propia, total o parcial, pero es posible que lo acepten sin financiación o con la condición de obtener financiación de alguna otra institución. En cambio, casi ningún programa de maestría ofrece financiación propia. 


## Para leer/explorar

- Paul Dudenhefer's [*Guide to the economics PhD*](https://www.pauldudenhefer.net/introduction).

- AEA. [Considerations for prospective graduate students in economics](https://www.aeaweb.org/resources/students/grad-prep/considerations). 

- Chris Blattman. [Which Master’s program is for you?](https://chrisblattman.com/blog/2017/10/04/what-ma-mpa-or-mia-program-is-for-you/)

- [Pathways to Research and Doctoral Careers (PREDOC).](https://predoc.org)

- [INOMICS - The site for economists](https://inomics.com).

- Calarco, Jessica. 2020. *A Field Guide to Grad School: Uncovering the Hidden Curriculum*. Princeton University Press.

- Mejía, Javier. 2024. [Aplicar a un doctorado en una universidad top: tres cosas que pensar antes](https://forbes.co/2024/10/22/actualidad/aplicar-a-un-doctorado-en-una-universidad-top-tres-cosas-que-pensar-antes). *Forbes*. 

- Programas de becas y financiamiento:

    - [Banco de la República](https://www.banrep.gov.co/es/contenidos/programas-estudios-el-exterior).
    - [Colfuturo](https://www.colfuturo.org).
    - [Campus France](https://www.colombie.campusfrance.org).
    - [DAAD](https://www.daad.de/en/studying-in-germany/).
    - [Fullbright](https://fulbright.edu.co).
    - [Chevening](https://www.chevening.org/scholarship/colombia/).