---
title: Contenido sobre economía [en construcción]
---

Esta es una lista de contenidos, en diferentes formatos, sobre economía. Desde luego no es una lista exhaustiva y además está claramente sesgada hacia mis intereses (macro y banca central).

## Coyuntura y política económica
### Prensa/blogs/etc.
La prensa especializada en economía en Colombia es bastante regular pero vale la pena revisarla de vez en cuando---y *algunas* de las columnas regulares suelen ser buenas:

- [Portafolio](https://www.portafolio.co)

- [La República](https://www.larepublica.co)


Hay cosas más interesantes en las secciones de economía de periódicos, revistas y portales generalistas:

- [La Silla Vacía](https://www.lasillavacia.com)

- [El Espectador](https://www.elespectador.com/economia/)

- [Razón Pública](https://razonpublica.com/categoria/temas/economia-y-sociedad/)

- [Contexto](https://contextomedia.com) [De vez en cuando] 


El Banco de la República, los tanques de pensamiento, las universidades y las unidades de investigación económica de instituciones financieras producen informes y notas de diverso tipo, y de muy buena calidad, sobre la coyuntura y la política económica en general:

- [Blog del Banrep](https://www.banrep.gov.co/es/blog)

- [Boletín Económico Regional (Banrep)](https://www.banrep.gov.co/es/publicaciones-investigaciones/boletin-economico-regional)

- [Ensayos Sobre Política Económica (Banrep)](https://investiga.banrep.gov.co/es/espe/numero-actual)

- [Informe de Política Monetaria (Banrep)](https://repositorio.banrep.gov.co/collections/f8573ac9-0697-4eb9-a1e3-bda3bd346f39)

- [Reporte de Estabilidad Financiera (Banrep)](https://repositorio.banrep.gov.co/collections/6219013a-8e84-43b2-8795-355bd3f0a4de)

- [Reporte de Mercado Laboral (Banrep)](https://repositorio.banrep.gov.co/collections/145d2f85-619e-4b03-81ad-cac61cb15613)

- [Fedesarrollo](https://fedesarrollo.org.co/p/publicaciones)

- [Nota Macroeconómica (Universidad de los Andes)](https://economia.uniandes.edu.co/publicaciones)

- [Informes del Observatorio Fiscal de la Universidad Javeriana](https://www.ofiscal.org/informes)

- [BBVA Research - Colombia](https://www.bbvaresearch.com/geography/colombia/)

- [Corficolombiana - Investigaciones](https://investigaciones.corfi.com)

- [Bancolombia - Investigaciones Económicas](https://www.bancolombia.com/empresas/capital-inteligente/investigaciones-economicas)

- [Fundación WWB Colombia](https://www.fundacionwwbcolombia.org/sala-de-publicaciones/publicaciones-propias/informes-tecnicos/)




Sobre las discusiones internacionales hay una infinidad de recusos, pero estos pueden ser un buen lugar para empezar:

- [The Economist](https://www.economist.com) [Disponible vía ProQuest]

- [Financial Times](https://www.ft.com) [Disponible vía ProQuest, con embargo]

- [VoxEU (CEPR)](https://cepr.org/voxeu)

- [Brookings Institution](https://www.brookings.edu)

- [Liberty Street Economics (NY Fed)](https://libertystreeteconomics.newyorkfed.org/)

- [Bank Underground (BoE)](https://bankunderground.co.uk/)

- [BIS Bulletins](https://www.bis.org/bisbulletins/index.htm)

- [Finance and Development (IMF)](https://www.imf.org/en/Publications/fandd)

- [Phenomenal World](https://www.phenomenalworld.org)

- [Claudia Sahm, Stay-At-Home Macro - Substack](https://stayathomemacro.substack.com/)

- [Brad Delong, Grasping Reality - Substack](https://braddelong.substack.com)

- [Marginal Revolution](https://marginalrevolution.com)

- [#EconSky (@Bluesky)](https://bsky.app/profile/paulgp.com/feed/aaabqfmu2zuck)


### Podcasts y YouTube
- [Economía para la pipol](https://www.youtube.com/@economiaparalapipol/videos)

- [Políticas Públicas](https://www.youtube.com/@politicaspublicascol/videos)

- [Atemporal](https://www.youtube.com/@atemporalpodcast) [A veces entrevistan a economistas/gente relacionada con política económica]

- [Cuentas y cuentos (Banrep)](https://www.banrep.gov.co/es/podcast)

- [Macromusings](https://macromusings.libsyn.com/)

- [Capitalism and Freedom in the Twenty-First Century](https://www.capitalismandfreedom.com)

- [IMF Podcasts](https://www.imf.org/en/News/Podcasts)

- [VoxTalks (CEPR)](https://cepr.org/voxeu/voxtalks)

- [BISness (BIS)](https://bispodcast.libsyn.com)

- [Odd Lots](https://www.bloomberg.com/oddlots)

- [Planet Money](https://www.npr.org/sections/money/)

- [CNBC](https://www.youtube.com/@CNBC)

## Publicaciones académicas
...





